---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-app
  template:
    metadata:
      labels:
        app: go-app
    spec:
      initContainers:
        - name: go-app-wait-db
          image: busybox:1.28
          command: ['sh', '-c', "until nslookup db.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for DB; sleep 2; done"]

        - name: go-app-migrate
          image: h1b/go-app
          imagePullPolicy: Never
          command: ["/usr/local/bin/backend", "migrate", "up"]
          env:
            - name: DB_STRING
              value: "root:root@tcp(db:3306)/myapp"

      containers:
        - name: go-app
          image: h1b/go-app
          imagePullPolicy: Never
          env:
            - name: DB_STRING
              value: "root:root@tcp(db:3306)/myapp"
          resources:
            limits:
              memory: "200Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
              name: go-app-http
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: go-app
spec:
  type: ClusterIP
  selector:
    app: go-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: go-app-http
