---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-app-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: next-app
  template:
    metadata:
      labels:
        app: next-app
    spec:
      initContainers:
        - name: next-app-wait-backend
          image: busybox:1.28
          command: ['sh', '-c', "until nslookup go-app.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for DB; sleep 2; done"]

      containers:
        - name: next-app
          image: h1b/nodejs-app
          imagePullPolicy: Never
          env:
            - name: BACKEND_URL
              value: "http://go-app:80"
          resources:
            limits:
              memory: "1Gi"
              cpu: "1000m"
          ports:
            - containerPort: 3000
              name: next-app-http
          readinessProbe:
            httpGet:
              path: /
              port: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: next-app
spec:
  type: LoadBalancer
  selector:
    app: next-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: next-app-http
